### ISSUE TITLE
无法在Windows正常使用

### ISSUE THREAD

**Issue by INSide-734** [TownesZhou/zhenxun_plugin_waifulabs#1]
无报错，返回无图片

**Comment by FengXin2125** [comment]
可以运行 可是太慢了。。。

**Comment by FengXin2125** [comment]
![image](https://user-images.githubusercontent.com/109187007/184558560-aada695e-c11b-46ca-b31b-c80dda6d1dbd.png)

**Comment by FengXin2125** [comment]
https://github.com/FengXin2125/zhenxun_plugin_waifulabs
